require:
 - 'test_prof/rubocop'

AllCops:
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/*'
    - 'db/fixtures/**/*'
    - 'db/migrate/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'config.ru'
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 39

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'spec/**/shared_examples/*.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'
  AllowedMethods: ['guard', 'included']

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/*

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile

Metrics/MethodLength:
  Max: 50
  Exclude:
    - app/controllers/concerns/recoverable.rb

Metrics/PerceivedComplexity:
  Max: 10

Naming/MethodParameterName:
  MinNameLength: 2

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - Rakefile
    - config/application.rb
    - config/environments/*
    - config/routes.rb
    - db/seeds.rb

Style/GlobalStdStream:
  Exclude:
    - config/environments/*

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'
  Exclude:
    - Gemfile

Style/RedundantConstantBase:
  Exclude:
    - config/environments/*

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

